CREATE ROLE editor NOLOGIN;
GRANT editor TO app_user;
GRANT ALL PRIVILEGES ON SCHEMA api TO editor;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA api TO editor;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA api TO editor;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA api TO editor;
